name: Bug Report
description: Report a bug or issue with QAstell
title: "[Bug]: "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        ⚠️ **Security Notice**: Please avoid including confidential or sensitive information in your bug report. Stack traces, configuration files, and error logs can contain details that—when combined with other publicly available or leaked data—could potentially be used to compromise systems. Sanitize any code snippets, URLs, file paths, or credentials before posting.

  - type: dropdown
    id: license
    attributes:
      label: License Tier
      description: What license tier are you using?
      options:
        - Free
        - Enterprise
        - Corporate
    validations:
      required: true

  - type: dropdown
    id: framework
    attributes:
      label: Framework
      description: Which test framework are you using?
      options:
        - Playwright
        - Puppeteer
        - Cypress
        - Selenium WebDriver
        - WebDriverIO
    validations:
      required: true

  - type: input
    id: framework-version
    attributes:
      label: Framework Version
      description: "What version of your test framework are you using?"
      placeholder: "e.g., 1.49.0"
    validations:
      required: true

  - type: dropdown
    id: reporter
    attributes:
      label: Reporting Mechanism
      description: Which reporting mechanism are you using?
      options:
        - None / Built-in HTML
        - Allure
        - Mochawesome
        - Playwright HTML Reporter
        - Jest HTML Reporter
        - Cucumber
        - Other
    validations:
      required: true

  - type: input
    id: reporter-version
    attributes:
      label: Reporter Version
      description: "What version of your reporter are you using? (if applicable)"
      placeholder: "e.g., 3.4.0"
    validations:
      required: false

  - type: input
    id: version
    attributes:
      label: QAstell Version
      description: "What version of QAstell are you using? Run `npm ls qastell` or check your package.json"
      placeholder: "e.g., 0.6.1"
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: A clear description of the bug
      placeholder: What happened? What did you expect to happen?
    validations:
      required: true

  - type: textarea
    id: reproduction
    attributes:
      label: Steps to Reproduce
      description: How can we reproduce this issue?
      placeholder: |
        1. Create a test with...
        2. Run the audit...
        3. See error...
    validations:
      required: true

  - type: textarea
    id: environment
    attributes:
      label: Environment
      description: Please provide your environment details
      placeholder: |
        - OS: [e.g., Ubuntu 22.04, Windows 11, macOS 14]
        - Node.js version: [e.g., 20.10.0]
    validations:
      required: false
