name: Feature Request
description: Suggest a new feature or improvement
title: "[Feature]: "
labels: ["enhancement"]
body:
  - type: dropdown
    id: license
    attributes:
      label: License Tier
      description: What license tier are you using?
      options:
        - Free
        - Enterprise
        - Corporate
    validations:
      required: true

  - type: dropdown
    id: framework
    attributes:
      label: Framework
      description: Which test framework are you using? (Select the primary one if using multiple)
      options:
        - Playwright
        - Puppeteer
        - Cypress
        - Selenium WebDriver
        - Multiple / All
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Feature Description
      description: A clear description of the feature you'd like
      placeholder: Describe the feature and why it would be useful
    validations:
      required: true

  - type: textarea
    id: use-case
    attributes:
      label: Use Case
      description: What problem would this feature solve for you?
      placeholder: Explain your use case and how this feature would help
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Have you considered any alternative solutions or workarounds?
      placeholder: Describe any alternatives you've considered
    validations:
      required: false
