/**
 * QAstell + WebDriverIO 8 + Allure 2 (Stable) Integration Example
 *
 * This example demonstrates real-world security auditing using WebDriverIO 8
 * for browser automation with Allure 2 (stable) for test reporting.
 *
 * Uses https://the-internet.herokuapp.com - a reliable test automation
 * demo site with forms, login pages, and various UI patterns.
 *
 * WebDriverIO 8 with Allure 2 provides stable, production-ready reporting.
 */

// WebDriverIO globals (injected by framework at runtime)
// eslint-disable-next-line @typescript-eslint/no-explicit-any
declare const browser: any;
// eslint-disable-next-line @typescript-eslint/no-explicit-any
declare const expect: any;

import {
  SecurityAuditor,
  AuditResults,
  VERSION,
  getTierDisplayName,
  createWebDriverIOAdapter,
} from 'qastell';
import AllureReporter from '@wdio/allure-reporter';
import * as fs from 'fs';
import * as path from 'path';

const BASE_URL = 'https://the-internet.herokuapp.com';
const REPORT_DIR = path.join(process.cwd(), 'qastell-report');

// Ensure report directory exists
function ensureReportDir(): void {
  if (!fs.existsSync(REPORT_DIR)) {
    fs.mkdirSync(REPORT_DIR, { recursive: true });
  }
}

// Get QAstell info string from audit results
function getQAstellInfo(results: AuditResults): string {
  const tierName = getTierDisplayName(results.tier);
  return `QAstell v${VERSION} (${tierName})`;
}

// Save HTML report to disk and attach to Allure
function saveAndAttachReport(testName: string, results: AuditResults): string {
  ensureReportDir();
  const sanitizedName = testName.replace(/[^a-z0-9]/gi, '-').toLowerCase();
  const filename = `security-report-${sanitizedName}.html`;
  const filepath = path.join(REPORT_DIR, filename);
  fs.writeFileSync(filepath, results.toHTML());
  return filepath;
}

// Attach security results to Allure report
function attachSecurityResults(testName: string, results: AuditResults): void {
  const { summary, violations } = results;
  const qastallInfo = getQAstellInfo(results);

  AllureReporter.addLabel('epic', 'Security');
  AllureReporter.addLabel('feature', 'Security Audit');

  if (summary.bySeverity.critical > 0) {
    AllureReporter.addSeverity('critical');
  } else if (summary.bySeverity.high > 0) {
    AllureReporter.addSeverity('blocker');
  } else if (summary.bySeverity.medium > 0) {
    AllureReporter.addSeverity('normal');
  } else {
    AllureReporter.addSeverity('minor');
  }

  AllureReporter.addDescription(
    `
## Security Audit Results

**Generated by:** ${qastallInfo}
**URL:** ${results.raw.url}
**Status:** ${results.passed() ? '✅ PASSED' : '❌ FAILED'}
**Total Issues:** ${summary.total}

### By Severity
- Critical: ${summary.bySeverity.critical}
- High: ${summary.bySeverity.high}
- Medium: ${summary.bySeverity.medium}
- Low: ${summary.bySeverity.low}
- Info: ${summary.bySeverity.info}

${
  violations.length > 0
    ? `
### Top Violations
${violations
  .slice(0, 5)
  .map((v, i) => `${i + 1}. **[${v.rule?.severity?.toUpperCase()}]** ${v.rule?.name}: ${v.message}`)
  .join('\n')}
${violations.length > 5 ? `\n... and ${violations.length - 5} more` : ''}
`
    : ''
}
`.trim(),
    'markdown'
  );

  const reportPath = saveAndAttachReport(testName, results);
  AllureReporter.addAttachment('QAstell Security Report', fs.readFileSync(reportPath), 'text/html');

  const statusIcon = results.passed() ? '✅' : '❌';
  AllureReporter.addStep(`${statusIcon} Security Audit Complete: ${summary.total} issues found`);

  if (summary.bySeverity.critical > 0) {
    AllureReporter.addStep(`🔴 Critical: ${summary.bySeverity.critical} vulnerability(ies)`);
  }
  if (summary.bySeverity.high > 0) {
    AllureReporter.addStep(`🟠 High: ${summary.bySeverity.high} vulnerability(ies)`);
  }
  if (summary.bySeverity.medium > 0) {
    AllureReporter.addStep(`🟡 Medium: ${summary.bySeverity.medium} issue(s)`);
  }
  if (summary.bySeverity.low > 0) {
    AllureReporter.addStep(`🔵 Low: ${summary.bySeverity.low} issue(s)`);
  }
  if (summary.bySeverity.info > 0) {
    AllureReporter.addStep(`⚪ Info: ${summary.bySeverity.info} informational finding(s)`);
  }
}

// Assert that audit passed
function expectAuditPassed(results: AuditResults): void {
  if (results.passed()) return;

  const { summary, violations } = results;
  const lines = [
    `Security audit failed with ${summary.total} violation(s)`,
    `Generated by: ${getQAstellInfo(results)}`,
    '',
    'Summary:',
    `  Critical: ${summary.bySeverity.critical}`,
    `  High: ${summary.bySeverity.high}`,
    `  Medium: ${summary.bySeverity.medium}`,
    `  Low: ${summary.bySeverity.low}`,
    `  Info: ${summary.bySeverity.info}`,
    '',
    'Violations:',
  ];

  violations.forEach((v, i) => {
    lines.push(`  ${i + 1}. [${v.rule?.severity?.toUpperCase()}] ${v.rule?.name}`);
    lines.push(`     ${v.message}`);
  });

  const error = new Error(lines.join('\n'));
  Error.captureStackTrace(error, expectAuditPassed);
  throw error;
}

// Create a SecurityAuditor from WebDriverIO browser
async function createAuditor(): Promise<SecurityAuditor> {
  const adapter = createWebDriverIOAdapter(browser);
  await adapter.init();
  return new SecurityAuditor(adapter as unknown as ConstructorParameters<typeof SecurityAuditor>[0]);
}

describe('Security Audit Demo @security', () => {
  it('should audit the homepage', async () => {
    AllureReporter.addFeature('Homepage Security');
    AllureReporter.addStory('Landing Page Audit');

    await browser.url(BASE_URL);
    await browser.waitUntil(async () => (await browser.$('h1')).isDisplayed(), { timeout: 15000 });

    const auditor = await createAuditor();
    const results = await auditor.audit();

    attachSecurityResults('homepage', results);
    console.log(`Homepage: ${results.summary.total} issues`);

    expectAuditPassed(results);
  });

  it('should audit the login page', async () => {
    AllureReporter.addFeature('Authentication Security');
    AllureReporter.addStory('Login Page Audit');

    await browser.url(`${BASE_URL}/login`);
    await browser.waitUntil(async () => (await browser.$('form')).isDisplayed(), { timeout: 15000 });

    const auditor = await createAuditor();
    const results = await auditor.audit({
      include: ['forms', 'sensitive-data', 'headers'],
    });

    attachSecurityResults('login-page', results);

    const formIssues = results.violations.filter((v) => v.rule?.category === 'forms');
    console.log(`Login Page: ${results.summary.total} issues (${formIssues.length} form-related)`);

    expectAuditPassed(results);
  });

  it('should audit the checkboxes page', async () => {
    AllureReporter.addFeature('Form Elements');
    AllureReporter.addStory('Checkboxes Audit');

    await browser.url(`${BASE_URL}/checkboxes`);
    await browser.waitUntil(async () => (await browser.$('input[type="checkbox"]')).isDisplayed(), {
      timeout: 15000,
    });

    const auditor = await createAuditor();
    const results = await auditor.audit();

    attachSecurityResults('checkboxes-page', results);
    console.log(`Checkboxes Page: ${results.summary.total} issues`);

    expectAuditPassed(results);
  });

  it('should audit the dropdown page', async () => {
    AllureReporter.addFeature('Form Elements');
    AllureReporter.addStory('Dropdown Audit');

    await browser.url(`${BASE_URL}/dropdown`);
    await browser.waitUntil(async () => (await browser.$('select')).isDisplayed(), { timeout: 15000 });

    const auditor = await createAuditor();
    const results = await auditor.audit();

    attachSecurityResults('dropdown-page', results);
    console.log(`Dropdown Page: ${results.summary.total} issues`);

    expectAuditPassed(results);
  });

  it('should audit dynamic content page', async () => {
    AllureReporter.addFeature('Dynamic Content');
    AllureReporter.addStory('Dynamic Content Audit');

    await browser.url(`${BASE_URL}/dynamic_content`);
    await browser.waitUntil(async () => (await browser.$('.large-10')).isDisplayed(), { timeout: 15000 });

    const auditor = await createAuditor();
    const results = await auditor.audit();

    attachSecurityResults('dynamic-content-page', results);
    console.log(`Dynamic Content Page: ${results.summary.total} issues`);

    expectAuditPassed(results);
  });
});

describe('Report Format Tests @security', () => {
  it('should generate HTML report', async () => {
    AllureReporter.addFeature('Report Generation');
    AllureReporter.addStory('HTML Report');

    await browser.url(BASE_URL);
    await browser.waitUntil(async () => (await browser.$('h1')).isDisplayed(), { timeout: 15000 });

    const auditor = await createAuditor();
    const results = await auditor.audit();
    const html = results.toHTML();

    console.log(`\nHTML Report Generated:`);
    console.log(`  Generated by: ${getQAstellInfo(results)}`);
    console.log(`  Size: ${Math.round(html.length / 1024)}KB`);

    attachSecurityResults('html-report-test', results);

    expect(html).toContain('<!DOCTYPE html>');
    expect(html).toContain('QAstell');
  });

  it('should generate summary HTML (smaller)', async () => {
    AllureReporter.addFeature('Report Generation');
    AllureReporter.addStory('Summary Report');

    await browser.url(BASE_URL);
    await browser.waitUntil(async () => (await browser.$('h1')).isDisplayed(), { timeout: 15000 });

    const auditor = await createAuditor();
    const results = await auditor.audit();
    const fullHtml = results.toHTML();
    const summaryHtml = results.toSummaryHTML();

    console.log(`\nReport Size Comparison:`);
    console.log(`  Generated by: ${getQAstellInfo(results)}`);
    console.log(`  Full Report: ${Math.round(fullHtml.length / 1024)}KB`);
    console.log(`  Summary: ${Math.round(summaryHtml.length / 1024)}KB`);
    console.log(`  Reduction: ${Math.round((1 - summaryHtml.length / fullHtml.length) * 100)}%`);

    AllureReporter.addStep(`Full report: ${Math.round(fullHtml.length / 1024)}KB`);
    AllureReporter.addStep(`Summary report: ${Math.round(summaryHtml.length / 1024)}KB`);

    expect(summaryHtml.length).toBeLessThan(fullHtml.length);
  });
});
