/**
 * QAstell + WebDriverIO 8 + Allure 2 (Stable) Integration Example
 *
 * This example demonstrates real-world security auditing using WebDriverIO 8
 * for browser automation with Allure 2 (stable) for test reporting.
 *
 * Uses https://the-internet.herokuapp.com - a reliable test automation
 * demo site with forms, login pages, and various UI patterns.
 *
 * WebDriverIO 8 with Allure 2 provides stable, production-ready reporting.
 */

// WebDriverIO globals (injected by framework at runtime)
// eslint-disable-next-line @typescript-eslint/no-explicit-any
declare const browser: any;
// eslint-disable-next-line @typescript-eslint/no-explicit-any
declare const expect: any;

import {
  SecurityAuditor,
  AuditResults,
  VERSION,
  getTierDisplayName,
  createWebDriverIOAdapter,
} from 'qastell';
import { Allure2Connector } from 'qastell/connectors';
import AllureReporter from '@wdio/allure-reporter';

const BASE_URL = 'https://the-internet.herokuapp.com';
const connector = new Allure2Connector();

// Get QAstell info string from audit results
function getQAstellInfo(results: AuditResults): string {
  const tierName = getTierDisplayName(results.tier);
  return `QAstell v${VERSION} (${tierName})`;
}

// Assert that audit passed
function expectAuditPassed(results: AuditResults): void {
  if (results.passed()) return;

  const { summary, violations } = results;
  const lines = [
    `Security audit failed with ${summary.total} violation(s)`,
    `Generated by: ${getQAstellInfo(results)}`,
    '',
    'Summary:',
    `  Critical: ${summary.bySeverity.critical}`,
    `  High: ${summary.bySeverity.high}`,
    `  Medium: ${summary.bySeverity.medium}`,
    `  Low: ${summary.bySeverity.low}`,
    `  Info: ${summary.bySeverity.info}`,
    '',
    'Violations:',
  ];

  violations.forEach((v, i) => {
    lines.push(`  ${i + 1}. [${v.rule?.severity?.toUpperCase()}] ${v.rule?.name}`);
    lines.push(`     ${v.message}`);
  });

  const error = new Error(lines.join('\n'));
  Error.captureStackTrace(error, expectAuditPassed);
  throw error;
}

// Create a SecurityAuditor from WebDriverIO browser
async function createAuditor(): Promise<SecurityAuditor> {
  const adapter = createWebDriverIOAdapter(browser);
  await adapter.init();
  return new SecurityAuditor(adapter as unknown as ConstructorParameters<typeof SecurityAuditor>[0]);
}

describe('Security Audit Demo @security', () => {
  it('should audit the homepage', async () => {
    AllureReporter.addFeature('Homepage Security');
    AllureReporter.addStory('Landing Page Audit');

    await browser.url(BASE_URL);
    await browser.waitUntil(async () => (await browser.$('h1')).isDisplayed(), { timeout: 15000 });

    const auditor = await createAuditor();
    const results = await auditor.audit();

    // Use Allure2Connector to attach summary with inline markdown
    await connector.attachSummary(results, AllureReporter);
    console.log(`Homepage: ${results.summary.total} issues`);

    expectAuditPassed(results);
  });

  it('should audit the login page', async () => {
    AllureReporter.addFeature('Authentication Security');
    AllureReporter.addStory('Login Page Audit');

    await browser.url(`${BASE_URL}/login`);
    await browser.waitUntil(async () => (await browser.$('form')).isDisplayed(), { timeout: 15000 });

    const auditor = await createAuditor();
    const results = await auditor.audit({
      include: ['forms', 'sensitive-data', 'headers'],
    });

    await connector.attachSummary(results, AllureReporter);

    const formIssues = results.violations.filter((v) => v.rule?.category === 'forms');
    console.log(`Login Page: ${results.summary.total} issues (${formIssues.length} form-related)`);

    expectAuditPassed(results);
  });

  it('should audit the checkboxes page', async () => {
    AllureReporter.addFeature('Form Elements');
    AllureReporter.addStory('Checkboxes Audit');

    await browser.url(`${BASE_URL}/checkboxes`);
    await browser.waitUntil(async () => (await browser.$('input[type="checkbox"]')).isDisplayed(), {
      timeout: 15000,
    });

    const auditor = await createAuditor();
    const results = await auditor.audit();

    await connector.attachSummary(results, AllureReporter);
    console.log(`Checkboxes Page: ${results.summary.total} issues`);

    expectAuditPassed(results);
  });

  it('should audit the dropdown page', async () => {
    AllureReporter.addFeature('Form Elements');
    AllureReporter.addStory('Dropdown Audit');

    await browser.url(`${BASE_URL}/dropdown`);
    await browser.waitUntil(async () => (await browser.$('select')).isDisplayed(), { timeout: 15000 });

    const auditor = await createAuditor();
    const results = await auditor.audit();

    await connector.attachSummary(results, AllureReporter);
    console.log(`Dropdown Page: ${results.summary.total} issues`);

    expectAuditPassed(results);
  });

  it('should audit dynamic content page', async () => {
    AllureReporter.addFeature('Dynamic Content');
    AllureReporter.addStory('Dynamic Content Audit');

    await browser.url(`${BASE_URL}/dynamic_content`);
    await browser.waitUntil(async () => (await browser.$('.large-10')).isDisplayed(), { timeout: 15000 });

    const auditor = await createAuditor();
    const results = await auditor.audit();

    await connector.attachSummary(results, AllureReporter);
    console.log(`Dynamic Content Page: ${results.summary.total} issues`);

    expectAuditPassed(results);
  });
});

describe('Report Format Tests @security', () => {
  it('should generate HTML report', async () => {
    AllureReporter.addFeature('Report Generation');
    AllureReporter.addStory('HTML Report');

    await browser.url(BASE_URL);
    await browser.waitUntil(async () => (await browser.$('h1')).isDisplayed(), { timeout: 15000 });

    const auditor = await createAuditor();
    const results = await auditor.audit();
    const html = results.toHTML();

    console.log(`\nHTML Report Generated:`);
    console.log(`  Generated by: ${getQAstellInfo(results)}`);
    console.log(`  Size: ${Math.round(html.length / 1024)}KB`);

    await connector.attachSummary(results, AllureReporter);

    expect(html).toContain('<!DOCTYPE html>');
    expect(html).toContain('QAstell');
  });

  it('should generate summary HTML (smaller)', async () => {
    AllureReporter.addFeature('Report Generation');
    AllureReporter.addStory('Summary Report');

    await browser.url(BASE_URL);
    await browser.waitUntil(async () => (await browser.$('h1')).isDisplayed(), { timeout: 15000 });

    const auditor = await createAuditor();
    const results = await auditor.audit();
    const fullHtml = results.toHTML();
    const summaryHtml = results.toSummaryHTML();

    console.log(`\nReport Size Comparison:`);
    console.log(`  Generated by: ${getQAstellInfo(results)}`);
    console.log(`  Full Report: ${Math.round(fullHtml.length / 1024)}KB`);
    console.log(`  Summary: ${Math.round(summaryHtml.length / 1024)}KB`);
    console.log(`  Reduction: ${Math.round((1 - summaryHtml.length / fullHtml.length) * 100)}%`);

    AllureReporter.addStep(`Full report: ${Math.round(fullHtml.length / 1024)}KB`);
    AllureReporter.addStep(`Summary report: ${Math.round(summaryHtml.length / 1024)}KB`);

    expect(summaryHtml.length).toBeLessThan(fullHtml.length);
  });
});
